version: '3.8'
services:
  mysecrets-backend:
    build:
      context: ./server
      dockerfile: DockerFile
    image: naveenmraja/mysecrets-backend:1.0
    container_name: mysecrets-backend
    ports:
      - "8080:8080"
    env_file:
      - ./.env.backend
    volumes:
      - "/usr/mysecrets/server/node_modules"
      - "./server:/usr/mysecrets/server"
  nginx:
    build:
      context: .
      dockerfile: ./nginx/DockerFile
    image: naveenmraja/mysecrets-nginx:1.1
    container_name: nginx
    ports:
      - "8000:80"
    depends_on:
      - mysecrets-backend
    links:
      - mysecrets-backend