apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: mysecrets-backend
  template:
    metadata:
      labels:
        component: mysecrets-backend
    spec:
      containers:
        - name: mysecrets-backend
          image: naveenmraja/mysecrets-backend:1.0
          ports:
            - containerPort: 8080
          env:
            - name: NODE_ENV
              value: production
            - name: EXPRESS_SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-env-secrets
                  key: EXPRESS_SESSION_SECRET
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: backend-env-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-env-secrets
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: backend-env-secrets
                  key: AWS_REGION